blank_issues_enabled: false
contact_links:
  - name: 💬 General Question
    url: https://teams.microsoft.com/l/channel/19%3A0058fdbf4e354af5b670f1220d8df6b1%40thread.tacv2/Developers?groupId=0907acc8-53da-4b09-8cae-a688798e356f&tenantId=eacde02c-2910-4cd3-b74f-bf1fedff8469
    about: Ask a question or start a discussion about anything related to our work.